-- =============================================
-- UPDATE BUKU 6: Matematika
-- =============================================
UPDATE `books` SET 
  `author` = 'Dr. Rahman Hakim, M.Pd.',
  `description` = 'Buku teks Matematika untuk perguruan tinggi. Membahas kalkulus, aljabar linear, statistika, probabilitas, dan matematika diskrit secara komprehensif.',
  `price` = 85000,
  `publisher` = 'Penerbit Erlangga',
  `publication_date` = '2024-04-12',
  `content` = '<h2>Bab 1: Dasar-dasar Kalkulus</h2>
<p>Kalkulus adalah cabang matematika yang mempelajari perubahan. Dikembangkan secara independen oleh Isaac Newton dan Gottfried Wilhelm Leibniz pada abad ke-17, kalkulus telah menjadi alat fundamental dalam sains, teknik, ekonomi, dan banyak bidang lainnya. Kalkulus terbagi menjadi dua bagian utama: kalkulus diferensial yang mempelajari laju perubahan, dan kalkulus integral yang mempelajari akumulasi besaran.</p>
<p>Konsep limit adalah fondasi dari seluruh kalkulus. Secara intuitif, limit dari fungsi f(x) saat x mendekati a adalah nilai yang didekati f(x) ketika x semakin dekat dengan a. Definisi formal limit menggunakan epsilon-delta yang diperkenalkan oleh Karl Weierstrass memberikan kerangka matematis yang rigorous. Limit memungkinkan kita mendefinisikan turunan dan integral secara presisi, menghindari paradoks yang pernah membingungkan matematikawan sebelumnya.</p>
<p>Turunan (derivative) mengukur laju perubahan sesaat dari sebuah fungsi. Secara geometris, turunan di suatu titik merupakan kemiringan garis singgung pada kurva fungsi di titik tersebut. Aturan-aturan turunan meliputi: aturan pangkat (d/dx[xⁿ] = nxⁿ⁻¹), aturan perkalian (product rule), aturan pembagian (quotient rule), dan aturan rantai (chain rule). Turunan memiliki aplikasi luas dalam optimasi, laju terkait, dan analisis perilaku fungsi.</p>
<p>Integral adalah operasi kebalikan dari turunan. Integral tak tentu menghasilkan antiturunan atau keluarga fungsi yang turunannya sama dengan integrand. Integral tentu menghitung luas daerah di bawah kurva fungsi pada interval tertentu. Teorema Fundamental Kalkulus menghubungkan kedua konsep ini: integral tentu dapat dihitung menggunakan antiturunan. Teknik integrasi meliputi substitusi, integrasi parsial, pecahan parsial, dan substitusi trigonometri.</p>

<h2>Bab 2: Aljabar Linear</h2>
<p>Aljabar linear adalah cabang matematika yang mempelajari vektor, ruang vektor, transformasi linear, dan sistem persamaan linear. Bidang ini memiliki aplikasi yang sangat luas dalam ilmu komputer (machine learning, grafika komputer, kriptografi), fisika (mekanika kuantum, relativitas), ekonomi (model input-output), dan statistika (regresi, analisis komponen utama).</p>
<p>Matriks adalah susunan persegi panjang dari bilangan-bilangan yang merupakan objek fundamental dalam aljabar linear. Operasi matriks meliputi penjumlahan, perkalian skalar, perkalian matriks, transpos, dan inverse. Determinan matriks memberikan informasi penting tentang sifat-sifat transformasi linear yang direpresentasikan oleh matriks tersebut. Matriks dengan determinan nol disebut singular dan tidak memiliki inverse.</p>
<p>Sistem persamaan linear dapat direpresentasikan dalam bentuk matriks Ax = b, di mana A adalah matriks koefisien, x adalah vektor variabel, dan b adalah vektor konstanta. Metode eliminasi Gauss mengubah matriks augmented menjadi bentuk eselon baris untuk menentukan solusi. Sistem dapat memiliki solusi tunggal, tak hingga solusi, atau tidak memiliki solusi, tergantung pada rank matriks A dan matriks augmented.</p>
<p>Eigenvalue dan eigenvector adalah konsep kunci dalam aljabar linear yang memiliki aplikasi dalam analisis stabilitas, vibrasi mekanis, dan Principal Component Analysis (PCA) dalam machine learning. Jika Av = λv untuk matriks A, skalar λ, dan vektor tak-nol v, maka λ adalah eigenvalue dan v adalah eigenvector yang bersesuaian. Dekomposisi eigen memungkinkan pemahaman mendalam tentang sifat-sifat transformasi linear.</p>

<h2>Bab 3: Statistika dan Probabilitas</h2>
<p>Statistika adalah ilmu yang mempelajari pengumpulan, pengorganisasian, analisis, interpretasi, dan penyajian data. Statistika deskriptif meringkas data menggunakan ukuran pemusatan (mean, median, modus) dan ukuran penyebaran (range, varians, standar deviasi). Statistika inferensial menggunakan sampel data untuk menarik kesimpulan tentang populasi, melibatkan estimasi parameter dan pengujian hipotesis.</p>
<p>Probabilitas mengukur kemungkinan terjadinya suatu peristiwa, dinyatakan sebagai angka antara 0 (mustahil) dan 1 (pasti). Tiga interpretasi utama probabilitas adalah: klasik (berdasarkan ruang sampel yang seragam), frekuentis (berdasarkan frekuensi relatif dalam jangka panjang), dan Bayesian (berdasarkan derajat kepercayaan subjektif). Teorema Bayes memungkinkan pembaruan probabilitas berdasarkan bukti baru dan menjadi fondasi dari metode Bayesian dalam statistika dan machine learning.</p>
<p>Distribusi probabilitas mendeskripsikan bagaimana probabilitas tersebar di antara nilai-nilai yang mungkin dari variabel acak. Distribusi diskrit penting meliputi Bernoulli, Binomial, Poisson, dan Geometrik. Distribusi kontinu penting meliputi Normal (Gaussian), Eksponensial, Uniform, dan t-Student. Distribusi normal memiliki peran sentral dalam statistika berkat Central Limit Theorem yang menyatakan bahwa rata-rata sampel dari populasi apa pun mendekati distribusi normal untuk ukuran sampel yang cukup besar.</p>

<h2>Bab 4: Matematika Diskrit</h2>
<p>Matematika diskrit mempelajari struktur matematis yang bersifat diskrit (tidak kontinu), berbeda dengan kalkulus yang berurusan dengan kuantitas kontinu. Bidang ini sangat relevan untuk ilmu komputer karena komputer digital beroperasi pada data diskrit. Topik-topik utama meliputi logika, himpunan, relasi, fungsi, kombinatorika, teori graf, dan teori bilangan.</p>
<p>Logika proposisional dan predikat menjadi fondasi dalam perancangan sirkuit digital, pemrograman, dan pembuktian matematis. Operator logika dasar — konjungsi (AND), disjungsi (OR), negasi (NOT), implikasi, dan biimplikasi — digunakan untuk membangun ekspresi logika yang kompleks. Tabel kebenaran dan hukum-hukum logika seperti De Morgan, distributif, dan absorpsi membantu menyederhanakan dan menganalisis ekspresi logika.</p>
<p>Teori graf mempelajari graf — objek matematis yang terdiri dari simpul (vertex) dan sisi (edge) yang menghubungkan simpul-simpul. Aplikasi teori graf mencakup jaringan sosial, peta rute, penjadwalan, dan optimasi. Algoritma-algoritma graf penting meliputi Breadth-First Search (BFS) dan Depth-First Search (DFS) untuk penjelajahan, algoritma Dijkstra untuk jalur terpendek, dan algoritma Kruskal atau Prim untuk minimum spanning tree.</p>
<p>Kombinatorika mempelajari cara menghitung pengaturan objek. Prinsip perkalian dan penjumlahan menjadi dasar penghitungan. Permutasi menghitung susunan terurut dari objek-objek, sementara kombinasi menghitung pemilihan tanpa memperhatikan urutan. Koefisien binomial C(n,k) = n!/(k!(n-k)!) menghitung banyaknya cara memilih k objek dari n objek, dan muncul dalam ekspansi binomial (Teorema Binomial Newton).</p>'
WHERE `id` = 6;

-- =============================================
-- UPDATE BUKU 7: Sejarah Indonesia
-- =============================================
UPDATE `books` SET 
  `author` = 'Prof. Dr. Samsul Farid, M.Hum.',
  `description` = 'Buku teks Sejarah Indonesia dari masa praaksara hingga era reformasi. Membahas kerajaan-kerajaan Nusantara, kolonialisme, perjuangan kemerdekaan, dan pembangunan nasional.',
  `price` = 72000,
  `publisher` = 'Penerbit Yrama Widya',
  `publication_date` = '2024-01-25',
  `category_id` = 2,
  `content` = '<h2>Bab 1: Indonesia Masa Praaksara</h2>
<p>Kepulauan Indonesia memiliki sejarah peradaban yang sangat panjang, jauh sebelum catatan tertulis pertama dibuat. Bukti-bukti arkeologis menunjukkan bahwa Nusantara telah dihuni oleh manusia purba sejak ratusan ribu tahun yang lalu. Penemuan fosil Homo erectus di Trinil, Jawa Timur oleh Eugene Dubois pada tahun 1891 — yang dikenal sebagai Java Man atau Pithecanthropus erectus — membuktikan bahwa pulau Jawa merupakan salah satu tempat tinggal manusia purba tertua di dunia.</p>
<p>Masa praaksara dibagi menjadi beberapa periode berdasarkan teknologi alat yang digunakan. Zaman Batu Tua (Paleolitikum) ditandai dengan penggunaan alat-alat batu yang kasar seperti kapak genggam dan chopper. Zaman Batu Tengah (Mesolitikum) melihat penghalusan teknik pembuatan alat dan munculnya kehidupan semi-menetap. Zaman Batu Muda (Neolitikum) membawa revolusi pertanian — manusia mulai bercocok tanam, memelihara hewan, dan membangun pemukiman permanen.</p>
<p>Migrasi besar-besaran bangsa Austronesia dari Taiwan ke kepulauan Nusantara yang terjadi sekitar 4.000-3.000 tahun yang lalu membawa perubahan signifikan. Para migran ini membawa teknologi pertanian padi basah, teknik pembuatan keramik, kemampuan navigasi laut yang unggul, dan bahasa yang menjadi nenek moyang dari ratusan bahasa daerah yang ada di Indonesia saat ini. Kebudayaan perunggu dan besi kemudian berkembang, ditandai dengan artefak-artefak seperti nekara perunggu dari Dongson dan berbagai peralatan logam.</p>

<h2>Bab 2: Kerajaan-kerajaan Hindu-Buddha di Nusantara</h2>
<p>Pengaruh kebudayaan India mulai masuk ke Nusantara sekitar awal abad Masehi melalui jalur perdagangan maritim. Kerajaan Kutai di Kalimantan Timur, yang didirikan sekitar abad ke-4, dianggap sebagai kerajaan Hindu tertua di Indonesia berdasarkan prasasti Yupa yang ditemukan di muara Sungai Mahakam. Kerajaan Tarumanagara di Jawa Barat, yang didirikan oleh Purnawarman pada abad ke-5, meninggalkan jejak berupa prasasti-prasasti yang bertuliskan huruf Pallawa dan bahasa Sanskerta.</p>
<p>Kerajaan Sriwijaya yang berpusat di Palembang, Sumatera Selatan, muncul pada abad ke-7 dan berkembang menjadi kerajaan maritim terbesar di Asia Tenggara. Sriwijaya menguasai Selat Malaka — jalur perdagangan paling penting antara Tiongkok dan India — selama beberapa abad. Kerajaan ini juga menjadi pusat pembelajaran agama Buddha yang terkenal, menarik peziarah dan cendekiawan dari berbagai negeri termasuk I-Tsing dari Tiongkok yang tinggal di Sriwijaya selama enam bulan untuk mempelajari tata bahasa Sanskerta.</p>
<p>Di Jawa Tengah, Dinasti Sailendra membangun kompleks candi Buddha terbesar di dunia — Candi Borobudur — pada abad ke-8 hingga ke-9. Monumen yang terdiri dari sembilan tingkat bertingkat ini memuat lebih dari 2.600 panel relief dan 504 arca Buddha, merupakan mahakarya arsitektur dan seni yang mencerminkan kedalaman filosofi Buddha. Tak jauh dari Borobudur, Candi Prambanan yang dibangun oleh dinasti Sanjaya merupakan kompleks candi Hindu terbesar di Indonesia, didedikasikan untuk Trimurti — Brahma, Wisnu, dan Siwa.</p>
<p>Kerajaan Majapahit, yang didirikan oleh Raden Wijaya pada tahun 1293, mencapai puncak kejayaannya di bawah pemerintahan Hayam Wuruk dengan mahapatihnya Gajah Mada. Sumpah Palapa yang diucapkan Gajah Mada — berjanji tidak akan menikmati palapa (bumbu makanan/kenikmatan duniawi) sebelum berhasil menyatukan Nusantara — mencerminkan ambisi persatuan yang luas. Kitab Negarakretagama karya Mpu Prapanca dan Kitab Sutasoma karya Mpu Tantular (yang memuat semboyan Bhinneka Tunggal Ika) menjadi warisan sastra yang tak ternilai.</p>

<h2>Bab 3: Masa Kolonialisme</h2>
<p>Kedatangan bangsa Eropa ke Nusantara dimulai dengan ekspedisi Portugis yang berhasil menaklukkan Malaka pada tahun 1511 di bawah pimpinan Alfonso de Albuquerque. Motivasi utama mereka adalah monopoli perdagangan rempah-rempah — terutama cengkeh, pala, dan lada — yang pada masa itu bernilai setara emas di pasar Eropa. Bangsa Spanyol, Inggris, dan Belanda segera menyusul, memulai era persaingan kolonial di Asia Tenggara.</p>
<p>Verenigde Oost-Indische Compagnie (VOC) atau Kongsi Dagang Hindia Timur Belanda didirikan pada tahun 1602 sebagai perusahaan dagang yang memiliki wewenang quasi-pemerintahan. VOC membangun markas besarnya di Batavia (sekarang Jakarta) pada tahun 1619 dan secara bertahap memperluas pengaruhnya di seluruh Nusantara melalui kombinasi diplomasi, monopoli perdagangan, dan kekuatan militer. Sistem tanam paksa (cultuurstelsel) yang diperkenalkan oleh Gubernur Jenderal Johannes van den Bosch pada tahun 1830 memaksa petani Jawa menanam tanaman ekspor seperti kopi, tebu, dan nila di sepertiga lahan mereka.</p>
<p>Perlawanan rakyat Indonesia terhadap kolonialisme terjadi di berbagai daerah. Perang Padri (1803-1837) di Sumatera Barat, Perang Diponegoro (1825-1830) di Jawa, Perang Banjar (1859-1905) di Kalimantan, dan Perang Aceh (1873-1914) yang merupakan perang terlama dan paling menelan korban bagi Belanda. Tokoh-tokoh seperti Pangeran Diponegoro, Imam Bonjol, Teuku Umar, Cut Nyak Dhien, dan Sultan Hasanuddin menjadi simbol keberanian dan perlawanan terhadap penindasan kolonial.</p>

<h2>Bab 4: Pergerakan Nasional dan Kemerdekaan</h2>
<p>Awal abad ke-20 menandai babak baru dalam sejarah Indonesia dengan munculnya kesadaran nasional yang modern. Politik Etis Belanda yang diluncurkan pada tahun 1901 — meskipun motif utamanya adalah kepentingan kolonial — membuka akses pendidikan barat bagi sebagian kecil pribumi. Lulusan-lulusan sekolah Belanda inilah yang kemudian menjadi pelopor pergerakan nasional.</p>
<p>Budi Utomo, didirikan pada 20 Mei 1908 oleh Dr. Sutomo dan mahasiswa STOVIA, dianggap sebagai organisasi pergerakan nasional modern pertama. Disusul oleh Sarekat Islam (1912), Indische Partij (1912) yang dipimpin oleh Tiga Serangkai — Douwes Dekker, Tjipto Mangunkusumo, dan Ki Hajar Dewantara — dan berbagai organisasi lainnya. Kongres Pemuda II pada 28 Oktober 1928 menghasilkan Sumpah Pemuda yang mempersatukan pemuda dari berbagai suku dalam ikrar satu tanah air, satu bangsa, dan satu bahasa.</p>
<p>Proklamasi Kemerdekaan Indonesia dibacakan oleh Soekarno dan Mohammad Hatta pada tanggal 17 Agustus 1945, dua hari setelah Jepang menyerah kepada Sekutu dalam Perang Dunia II. Naskah proklamasi yang singkat namun bersejarah itu ditandatangani atas nama bangsa Indonesia oleh Soekarno-Hatta. Kemerdekaan tidak serta-merta diakui oleh Belanda yang berupaya kembali menjajah, memicu perjuangan diplomatik dan bersenjata yang berlangsung hingga pengakuan kedaulatan pada 27 Desember 1949 melalui Konferensi Meja Bundar di Den Haag.</p>'
WHERE `id` = 7;
