-- =============================================
-- UPDATE BUKU 8: Bahasa Inggris Kelas X
-- =============================================
UPDATE `books` SET 
  `author` = 'Kementerian Pendidikan dan Kebudayaan',
  `description` = 'Buku teks Bahasa Inggris untuk siswa SMA/SMK Kelas X. Membahas speaking, listening, reading, dan writing secara komprehensif sesuai kurikulum nasional 2017.',
  `price` = 68000,
  `publisher` = 'Pusat Kurikulum dan Perbukuan, Kemendikbud',
  `publication_date` = '2017-01-01',
  `content` = '<h2>Chapter 1: Talking About Self</h2>
<p>Learning a new language is like opening a door to a whole new world. In this first chapter, we will learn how to introduce ourselves and others in English. Self-introduction is one of the most basic yet important skills in communication. Whether you are meeting new classmates, attending a job interview, or traveling abroad, knowing how to introduce yourself properly will give you confidence and make a great first impression.</p>
<p>When introducing yourself, there are several key pieces of information you might want to share: your name, where you come from, your age, your hobbies, and your occupation or school. For example: "Hello, my name is Rina. I am from Bandung, West Java. I am sixteen years old and I am a student at SMK Negeri 1 Bandung. I enjoy reading books and playing basketball in my free time." Notice how the sentences are simple, clear, and easy to understand.</p>
<p>Greetings are also an important part of introduction. In English, we use different greetings depending on the time of day and the level of formality. "Good morning" is used before noon, "Good afternoon" from noon to around 5 PM, and "Good evening" after 5 PM. For informal situations, you can simply say "Hi" or "Hello." When meeting someone for the first time, you can say "Nice to meet you" or "Pleased to meet you." These small phrases show politeness and respect.</p>
<p>Pronouns play a crucial role in English. Unlike Bahasa Indonesia where "dia" is used for everyone, English distinguishes between "he" (laki-laki), "she" (perempuan), and "they" (mereka). Subject pronouns (I, you, he, she, it, we, they) are used as the subject of a sentence, while object pronouns (me, you, him, her, it, us, them) are used as the object. Possessive adjectives (my, your, his, her, its, our, their) show ownership. Mastering pronouns is essential for constructing correct English sentences.</p>

<h2>Chapter 2: Congratulating and Complimenting Others</h2>
<p>In everyday life, we often need to express our happiness for other people achievements or to give compliments about their appearance, work, or skills. Learning how to congratulate and compliment others in English is an important social skill that helps build positive relationships. A sincere compliment can brighten someone day and strengthen your bond with them.</p>
<p>Expressions of congratulation are used when someone achieves something special. Common expressions include: "Congratulations!", "Congratulations on your success!", "Well done!", "I am so proud of you!", and "That is fantastic news!" For example, if your friend wins a competition, you might say: "Congratulations on winning the science competition! You really deserved it. I know how hard you have been studying." The response to congratulations is usually "Thank you" or "Thanks a lot."</p>
<p>Complimenting is the act of saying something nice about someone or something. Compliments can be about appearance ("You look great today!", "That is a beautiful dress!"), ability ("You are such a talented singer!", "Your English is very good!"), or possessions ("What a nice car!", "I love your new phone!"). When receiving a compliment, it is polite to say "Thank you," "That is very kind of you," or "I appreciate that." In Indonesian culture, we might feel shy about receiving compliments, but in English-speaking cultures, accepting compliments gracefully is considered good manners.</p>
<p>The structure of complimenting sentences often uses exclamatory patterns with "What" and "How." "What a beautiful painting!" uses the pattern What + a/an + adjective + noun. "How clever you are!" uses the pattern How + adjective + subject + verb. These structures add emphasis and enthusiasm to your compliments, making them sound more natural and heartfelt.</p>

<h2>Chapter 3: Expressing Intention</h2>
<p>We often talk about things we plan to do in the future. In English, there are several ways to express intention, and each has its own nuance. Understanding these differences will help you communicate your plans more precisely. The most common ways to express intention are using "will," "be going to," "plan to," "intend to," and "would like to."</p>
<p>"Be going to" is used for plans that have already been decided. For example: "I am going to study medicine after I graduate from SMK" means you have already made this decision. "Will" can be used for spontaneous decisions made at the moment of speaking: "It is raining! I will take an umbrella." "Will" is also used for promises and predictions: "I will help you with your homework" or "I think it will rain tomorrow."</p>
<p>"Plan to" and "intend to" are more formal ways of expressing intention. "I plan to visit my grandmother next weekend" and "I intend to improve my English speaking skills this semester" both show a deliberate decision. "Would like to" is a polite way of expressing what you want to do: "I would like to become a software engineer someday." These expressions are very useful in formal contexts like interviews or presentations.</p>
<p>When asking about someone else intentions, you can use questions like: "What are you going to do this weekend?", "Do you have any plans for the holiday?", "What do you intend to do after graduation?", or "Would you like to join us for dinner?" Being able to ask and answer questions about intentions is essential for making plans with friends, discussing goals with teachers, and preparing for future conversations in professional settings.</p>

<h2>Chapter 4: Descriptive Text</h2>
<p>A descriptive text is a type of text that describes a particular person, place, animal, or thing in detail. The purpose of a descriptive text is to give the reader a clear picture of what is being described, as if they can see, hear, feel, smell, or taste it through your words. Good descriptive writing uses vivid adjectives and sensory details to bring the subject to life.</p>
<p>The generic structure of a descriptive text consists of two parts: Identification and Description. The Identification introduces the subject — who or what is being described. The Description provides detailed characteristics, qualities, or features of the subject. For example, when describing your school, the identification might be: "SMK Negeri 1 Bandung is one of the most prestigious vocational schools in West Java." The description would then elaborate on its location, facilities, programs, and atmosphere.</p>
<p>Language features of descriptive texts include: the use of specific nouns (my cat Mimi, Borobudur Temple), varied adjectives (beautiful, enormous, ancient, sparkling), relating verbs or "to be" (is, are, was, were, has, have), action verbs to describe behavior (run, swim, fly, dance), and figurative language such as similes ("as white as snow") and metaphors ("the classroom was an oven"). Adverbs and prepositional phrases add information about how, where, and when.</p>
<p>Writing a good descriptive text requires careful observation and organization. Start with a general overview of the subject, then move to specific details. Use spatial order (from left to right, top to bottom) when describing places, and from general to specific when describing people or things. For example, when describing a person, you might start with their general appearance, then move to specific facial features, clothing, personality traits, and habits. Practice by describing objects around you — your classroom, your favorite food, or your best friend.</p>

<h2>Chapter 5: Announcement and Narrative Text</h2>
<p>An announcement is a public statement that provides information about something that has happened, is happening, or will happen. Announcements can be found in schools, offices, airports, train stations, and public places. In English, announcements follow a specific format that includes: a title or heading, the date and time, the target audience, the content of the announcement, and the contact person or organization making the announcement.</p>
<p>School announcements might include information about upcoming events, schedule changes, competition results, or important deadlines. For example: "Attention all students! The annual English Speech Competition will be held on Monday, March 15, 2025, at 9:00 AM in the school auditorium. Students who wish to participate must register with their English teacher before Friday, March 12. Prizes will be awarded to the top three speakers. For more information, please contact Ms. Dewi at the English Department."</p>
<p>A narrative text tells a story, either fictional or based on real events. The purpose of a narrative is to entertain, inform, or teach a moral lesson. The generic structure of a narrative text includes: Orientation (introducing characters, setting, and time), Complication (the problem or conflict that arises), Resolution (how the problem is solved), and sometimes a Coda or moral lesson. Fairy tales, legends, fables, myths, and personal experiences are all examples of narrative texts.</p>
<p>Language features of narrative texts include the use of past tense (walked, said, discovered), time connectives (once upon a time, then, after that, finally), specific character names, dialogue using direct and indirect speech, and descriptive language to create mood and atmosphere. Understanding narrative structure helps you not only in reading comprehension but also in writing your own stories. Practice by retelling your favorite Indonesian folktales in English — stories like Malin Kundang, Timun Mas, or Sangkuriang are great starting points for practicing narrative writing skills.</p>'
WHERE `id` = 8;
