-- =============================================
-- UPDATE BUKU 4: Fisika Modern
-- =============================================
UPDATE `books` SET 
  `author` = 'Prof. Dr. Hendra Wijaya, M.Si.',
  `description` = 'Buku teks Fisika Modern yang membahas mekanika kuantum, relativitas khusus, struktur atom, fisika nuklir, dan partikel elementer. Dilengkapi soal latihan dan pembahasan.',
  `price` = 98000,
  `publisher` = 'Penerbit Erlangga',
  `publication_date` = '2024-07-22',
  `content` = '<h2>Bab 1: Relativitas Khusus Einstein</h2>
<p>Pada akhir abad ke-19, fisika klasik tampak hampir sempurna. Mekanika Newton menjelaskan gerak benda-benda dari apel yang jatuh hingga planet yang mengorbit. Namun, beberapa eksperimen menghasilkan hasil yang tidak dapat dijelaskan oleh teori klasik. Salah satu yang paling terkenal adalah eksperimen Michelson-Morley pada tahun 1887 yang gagal mendeteksi keberadaan ether — medium hipotesis yang diyakini menjadi perantara perambatan cahaya.</p>
<p>Pada tahun 1905, Albert Einstein mempublikasikan teori relativitas khusus yang merevolusi pemahaman kita tentang ruang dan waktu. Teori ini didasarkan pada dua postulat sederhana: pertama, hukum-hukum fisika berlaku sama di semua kerangka acuan inersia; kedua, kecepatan cahaya dalam vakum adalah konstan untuk semua pengamat, tidak bergantung pada kecepatan sumber cahaya atau pengamat. Dari dua postulat ini, konsekuensi yang luar biasa muncul.</p>
<p>Dilasi waktu adalah salah satu prediksi paling menakjubkan dari relativitas khusus. Jam yang bergerak relatif terhadap pengamat akan berjalan lebih lambat dibandingkan jam yang diam. Efek ini bukan ilusi — ia telah diverifikasi berkali-kali menggunakan jam atom yang sangat presisi pada pesawat jet dan satelit GPS. Tanpa koreksi relativistik, sistem GPS akan mengakumulasi error posisi sekitar 10 kilometer per hari.</p>
<p>Persamaan paling terkenal dalam fisika, E = mc², juga lahir dari relativitas khusus. Persamaan ini menyatakan kesetaraan massa dan energi — sejumlah kecil massa dapat dikonversi menjadi energi yang sangat besar karena c² (kuadrat kecepatan cahaya) adalah angka yang sangat besar. Prinsip ini menjadi dasar reaksi nuklir dalam bintang, pembangkit listrik tenaga nuklir, dan sayangnya juga senjata nuklir.</p>

<h2>Bab 2: Mekanika Kuantum</h2>
<p>Mekanika kuantum adalah teori fisika yang mendeskripsikan perilaku materi dan energi pada skala atomik dan subatomik. Berbeda dengan fisika klasik yang deterministik — di mana posisi dan kecepatan partikel dapat ditentukan dengan pasti — mekanika kuantum bersifat probabilistik. Kita hanya dapat menghitung probabilitas menemukan partikel di suatu posisi tertentu.</p>
<p>Hipotesis kuantum pertama kali diajukan oleh Max Planck pada tahun 1900 untuk menjelaskan spektrum radiasi benda hitam. Planck mengusulkan bahwa energi dipancarkan dan diserap dalam paket-paket diskrit yang ia sebut kuanta. Energi setiap kuantum sebanding dengan frekuensi radiasi: E = hf, di mana h adalah konstanta Planck (6.626 × 10⁻³⁴ J·s). Ide revolusioner ini menandai kelahiran fisika kuantum.</p>
<p>Prinsip ketidakpastian Heisenberg menyatakan bahwa kita tidak dapat secara simultan mengetahui posisi dan momentum sebuah partikel dengan presisi sempurna. Semakin tepat kita mengukur posisi partikel, semakin tidak pasti momentumnya, dan sebaliknya. Ini bukan keterbatasan teknologi pengukuran, melainkan sifat fundamental dari alam. Prinsip ini memiliki implikasi filosofis yang mendalam tentang hakikat realitas dan peran pengamat dalam pengukuran.</p>
<p>Dualitas gelombang-partikel menunjukkan bahwa objek kuantum memiliki sifat gelombang dan partikel sekaligus. Eksperimen celah ganda mendemonstrasikan fenomena ini dengan indah: ketika elektron ditembakkan satu per satu melalui dua celah sempit, mereka secara individual mengenai layar detektor sebagai partikel, tetapi setelah banyak elektron ditembakkan, pola yang terbentuk adalah pola interferensi — ciri khas gelombang.</p>

<h2>Bab 3: Struktur Atom</h2>
<p>Pemahaman tentang struktur atom telah mengalami evolusi dramatis sepanjang sejarah ilmu pengetahuan. Model atom Dalton memandang atom sebagai bola padat yang tidak dapat dibagi. Penemuan elektron oleh J.J. Thomson pada tahun 1897 membawa model raisin pudding, di mana elektron bermuatan negatif tersebar dalam bola bermuatan positif.</p>
<p>Eksperimen hamburan partikel alfa oleh Ernest Rutherford pada tahun 1911 mengungkapkan bahwa sebagian besar massa atom terkonsentrasi di inti yang sangat kecil dan padat. Model atom Rutherford menggambarkan elektron mengorbit inti seperti planet mengorbit matahari. Namun, menurut elektrodinamika klasik, elektron yang dipercepat (bergerak melingkar) seharusnya meradiasikan energi dan akhirnya jatuh ke inti — yang jelas tidak terjadi.</p>
<p>Niels Bohr pada tahun 1913 menyelesaikan masalah ini dengan mengusulkan bahwa elektron hanya dapat menempati orbit-orbit tertentu dengan energi yang terkuantisasi. Elektron hanya memancarkan atau menyerap energi ketika berpindah antar orbit. Model Bohr berhasil menjelaskan spektrum emisi hidrogen, tetapi gagal untuk atom-atom yang lebih kompleks.</p>
<p>Model atom modern berdasarkan mekanika kuantum menggantikan konsep orbit dengan orbital — daerah ruang di mana probabilitas menemukan elektron paling tinggi. Persamaan Schrödinger menentukan fungsi gelombang elektron dalam atom, yang memberikan informasi lengkap tentang keadaan kuantum elektron. Bilangan kuantum — n (utama), l (azimuth), ml (magnetik), dan ms (spin) — secara unik mengidentifikasi setiap keadaan kuantum elektron dalam atom.</p>

<h2>Bab 4: Fisika Nuklir</h2>
<p>Fisika nuklir mempelajari struktur, sifat, dan interaksi inti atom. Inti atom terdiri dari proton dan neutron (secara kolektif disebut nukleon) yang terikat oleh gaya nuklir kuat — salah satu dari empat gaya fundamental alam. Gaya ini sangat kuat pada jarak pendek (sekitar 10⁻¹⁵ meter) tetapi menurun drastis pada jarak yang lebih besar, menjelaskan mengapa inti atom berukuran sangat kecil dibandingkan atom secara keseluruhan.</p>
<p>Radioaktivitas adalah proses di mana inti atom yang tidak stabil memancarkan partikel atau radiasi untuk mencapai konfigurasi yang lebih stabil. Terdapat tiga jenis peluruhan radioaktif utama: peluruhan alfa (memancarkan inti helium-4), peluruhan beta (mengubah neutron menjadi proton atau sebaliknya), dan peluruhan gamma (memancarkan foton energi tinggi). Setiap isotop radioaktif memiliki waktu paruh yang karakteristik — waktu yang diperlukan untuk separuh sampel meluruh.</p>
<p>Reaksi fisi nuklir melibatkan pembelahan inti berat (seperti uranium-235 atau plutonium-239) menjadi inti-inti yang lebih ringan, melepaskan energi yang sangat besar. Reaksi fusi nuklir, sebaliknya, menggabungkan inti-inti ringan (seperti deuterium dan tritium) menjadi inti yang lebih berat. Fusi adalah sumber energi bintang, termasuk Matahari kita, dan berpotensi menjadi sumber energi bersih yang hampir tak terbatas bagi umat manusia jika tantangan teknis dapat diatasi.</p>'
WHERE `id` = 4;

-- =============================================
-- UPDATE BUKU 5: Bahasa Indonesia
-- =============================================
UPDATE `books` SET 
  `author` = 'Dra. Kartini Suharto, M.Hum.',
  `description` = 'Buku panduan lengkap Bahasa Indonesia yang membahas ejaan, tata bahasa, penulisan karya ilmiah, sastra Indonesia, dan keterampilan berbahasa untuk tingkat SMA/Perguruan Tinggi.',
  `price` = 65000,
  `publisher` = 'Penerbit Yudhistira',
  `publication_date` = '2023-08-30',
  `content` = '<h2>Bab 1: Sejarah dan Perkembangan Bahasa Indonesia</h2>
<p>Bahasa Indonesia adalah bahasa resmi Republik Indonesia dan bahasa persatuan bangsa Indonesia. Bahasa ini berakar dari bahasa Melayu yang telah digunakan selama berabad-abad sebagai lingua franca di kepulauan Nusantara. Peristiwa bersejarah yang menegaskan kedudukan bahasa Indonesia adalah Sumpah Pemuda pada tanggal 28 Oktober 1928, di mana para pemuda dari berbagai suku bangsa menyatakan satu bahasa persatuan: Bahasa Indonesia.</p>
<p>Pilihan bahasa Melayu sebagai dasar bahasa Indonesia bukan tanpa alasan. Bahasa Melayu telah lama menjadi bahasa perdagangan dan diplomasi di Asia Tenggara. Struktur gramatikal bahasa Melayu relatif sederhana — tidak mengenal konjugasi kata kerja berdasarkan waktu, gender, atau jumlah seperti bahasa Eropa. Hal ini membuatnya lebih mudah dipelajari oleh penutur dari berbagai latar belakang bahasa daerah.</p>
<p>Sejak kemerdekaan Indonesia pada tahun 1945, Bahasa Indonesia terus mengalami perkembangan pesat. Ejaan yang digunakan telah berganti beberapa kali: dari Ejaan Van Ophuijsen (1901), Ejaan Republik (1947), Ejaan Yang Disempurnakan/EYD (1972), hingga Pedoman Umum Ejaan Bahasa Indonesia/PUEBI (2015). Setiap perubahan bertujuan untuk menyederhanakan dan menstandardisasi penulisan agar lebih konsisten dan mudah dipelajari.</p>

<h2>Bab 2: Ejaan dan Tata Tulis</h2>
<p>Ejaan yang benar merupakan aspek fundamental dalam komunikasi tertulis. Pedoman Umum Ejaan Bahasa Indonesia (PUEBI) mengatur penggunaan huruf kapital, huruf miring, tanda baca, penulisan kata, dan penulisan unsur serapan. Pemahaman yang baik tentang ejaan sangat penting bagi pelajar, mahasiswa, dan profesional untuk menghasilkan tulisan yang formal dan kredibel.</p>
<p>Huruf kapital digunakan pada awal kalimat, nama orang, nama tempat, nama hari dan bulan, gelar kehormatan yang diikuti nama, dan judul karya tulis. Kesalahan umum meliputi penggunaan huruf kapital yang berlebihan pada kata ganti dan penggunaan yang tidak konsisten. Tanda baca seperti titik, koma, titik koma, titik dua, tanda hubung, dan tanda pisah memiliki fungsi spesifik yang sering disalahgunakan dalam tulisan sehari-hari.</p>
<p>Penulisan unsur serapan dari bahasa asing mengikuti kaidah tertentu dalam PUEBI. Kata-kata yang diserap dari bahasa Inggris, Arab, Belanda, Portugis, Sanskerta, dan bahasa-bahasa lain telah menjadi bagian integral dari kosakata Bahasa Indonesia. Proses penyesuaian ejaan, misalnya "system" menjadi "sistem", "technology" menjadi "teknologi", dan "creative" menjadi "kreatif", mengikuti pola yang telah ditetapkan dalam pedoman resmi.</p>

<h2>Bab 3: Tata Bahasa Indonesia</h2>
<p>Tata bahasa Bahasa Indonesia mencakup morfologi (pembentukan kata) dan sintaksis (pembentukan kalimat). Dalam morfologi, proses pembentukan kata meliputi afiksasi (pembubuhan imbuhan), reduplikasi (pengulangan), dan komposisi (pemajemukan). Imbuhan dalam Bahasa Indonesia terdiri dari prefiks (awalan: me-, ber-, di-, ter-, pe-, se-, ke-), sufiks (akhiran: -kan, -an, -i), infiks (sisipan: -el-, -em-, -er-), dan konfiks (gabungan: ke-...-an, pe-...-an, ber-...-an).</p>
<p>Kalimat dalam Bahasa Indonesia umumnya mengikuti pola Subjek-Predikat-Objek (SPO), meskipun variasi urutan dimungkinkan untuk penekanan tertentu. Kalimat efektif memiliki ciri-ciri: kesepadanan struktur, keparalelan bentuk, ketegasan makna, kehematan penggunaan kata, kecermatan penalaran, kepaduan gagasan, dan kelogisan hubungan antarunsur.</p>
<p>Paragraf yang baik memiliki satu gagasan utama yang dikembangkan secara koheren. Kalimat topik menyatakan gagasan utama, sementara kalimat-kalimat penjelas memberikan dukungan, contoh, atau elaborasi. Koherensi antarkalimat dalam paragraf dicapai melalui penggunaan kata penghubung (konjungsi), pengulangan kata kunci, kata ganti, dan transisi logis yang menghubungkan ide satu dengan lainnya.</p>

<h2>Bab 4: Keterampilan Menulis Karya Ilmiah</h2>
<p>Karya ilmiah adalah tulisan yang disusun berdasarkan metodologi ilmiah, menggunakan bahasa baku, dan mengikuti konvensi akademik. Jenis-jenis karya ilmiah meliputi makalah, skripsi, tesis, disertasi, laporan penelitian, dan artikel jurnal. Setiap jenis memiliki struktur dan persyaratan yang berbeda, namun semuanya harus memenuhi prinsip objektivitas, sistematisitas, dan verifikabilitas.</p>
<p>Struktur umum karya ilmiah terdiri dari: pendahuluan (latar belakang masalah, rumusan masalah, tujuan, dan manfaat penelitian), kajian pustaka atau tinjauan literatur, metodologi penelitian, hasil dan pembahasan, serta kesimpulan dan saran. Setiap bagian memiliki fungsi spesifik dan harus ditulis dengan bahasa yang formal, lugas, dan tidak ambigu.</p>
<p>Pengutipan dan daftar pustaka merupakan komponen krusial dalam karya ilmiah untuk menghindari plagiarisme dan memberikan kredit kepada sumber informasi. Gaya pengutipan yang umum digunakan meliputi APA (American Psychological Association), MLA (Modern Language Association), Chicago, dan IEEE. Konsistensi dalam penggunaan gaya pengutipan sangat penting untuk menjaga kredibilitas dan profesionalisme karya ilmiah.</p>'
WHERE `id` = 5;
