-- =============================================
-- UPDATE BUKU 1: Teknik Informatika
-- =============================================
UPDATE `books` SET 
  `author` = 'Dr. Andi Prasetyo, M.Kom.',
  `description` = 'Buku panduan lengkap tentang dasar-dasar Teknik Informatika yang mencakup arsitektur komputer, sistem operasi, jaringan komputer, basis data, dan algoritma pemrograman. Cocok untuk mahasiswa semester awal jurusan Teknik Informatika.',
  `price` = 89000,
  `publisher` = 'Penerbit Informatika Bandung',
  `publication_date` = '2024-03-15',
  `content` = '<h2>Bab 1: Pengantar Teknik Informatika</h2>
<p>Teknik Informatika adalah cabang ilmu yang mempelajari bagaimana merancang, mengembangkan, dan mengelola sistem komputasi yang efisien dan andal. Disiplin ilmu ini menggabungkan konsep-konsep dari matematika, ilmu komputer, dan teknik untuk menciptakan solusi teknologi yang inovatif. Sejak kemunculan komputer pertama pada tahun 1940-an, bidang ini telah berkembang pesat hingga menjadi salah satu disiplin ilmu paling penting di era digital saat ini.</p>
<p>Dalam konteks pendidikan tinggi di Indonesia, program studi Teknik Informatika bertujuan menghasilkan lulusan yang mampu menganalisis, merancang, dan mengimplementasikan sistem perangkat lunak maupun perangkat keras. Mahasiswa tidak hanya diajarkan teori, tetapi juga keterampilan praktis yang dibutuhkan di dunia industri. Mulai dari pemrograman dasar hingga kecerdasan buatan, kurikulum dirancang agar relevan dengan kebutuhan pasar kerja yang terus berubah.</p>
<p>Salah satu aspek penting dalam Teknik Informatika adalah pemahaman tentang arsitektur komputer. Arsitektur komputer menjelaskan bagaimana komponen-komponen utama sebuah komputer — prosesor, memori, penyimpanan, dan perangkat I/O — saling berinteraksi. Pemahaman ini menjadi fondasi bagi seorang insinyur informatika dalam merancang sistem yang optimal, baik dari segi kinerja maupun efisiensi energi.</p>

<h2>Bab 2: Arsitektur Komputer dan Sistem Digital</h2>
<p>Arsitektur komputer merupakan fondasi dari setiap sistem komputasi modern. Pada tingkat paling dasar, komputer beroperasi menggunakan sistem bilangan biner — rangkaian angka 0 dan 1 yang merepresentasikan kondisi listrik hidup dan mati. Dari sistem sederhana ini, insinyur telah membangun mesin-mesin yang mampu melakukan miliaran perhitungan per detik.</p>
<p>Prosesor atau Central Processing Unit (CPU) adalah otak dari sebuah komputer. CPU modern terdiri dari miliaran transistor yang ditempatkan pada sebuah chip silikon berukuran kecil. Arsitektur Von Neumann, yang diperkenalkan oleh John von Neumann pada tahun 1945, masih menjadi dasar dari sebagian besar komputer saat ini. Dalam arsitektur ini, instruksi program dan data disimpan dalam memori yang sama, dan CPU mengambil serta mengeksekusi instruksi secara berurutan.</p>
<p>Selain CPU, komponen penting lainnya adalah memori. Random Access Memory (RAM) menyediakan ruang penyimpanan sementara yang dapat diakses dengan cepat oleh CPU. Semakin besar kapasitas RAM, semakin banyak data yang dapat diproses secara bersamaan. Di sisi lain, Read-Only Memory (ROM) menyimpan instruksi permanen yang dibutuhkan saat komputer pertama kali dinyalakan, seperti BIOS (Basic Input/Output System).</p>
<p>Sistem digital juga mencakup konsep gerbang logika — AND, OR, NOT, NAND, NOR, XOR — yang menjadi building block dari sirkuit digital. Kombinasi gerbang-gerbang ini membentuk sirkuit yang lebih kompleks seperti adder, multiplexer, dan flip-flop. Pemahaman mendalam tentang sistem digital memungkinkan insinyur untuk merancang komponen perangkat keras yang efisien dan handal.</p>

<h2>Bab 3: Sistem Operasi</h2>
<p>Sistem operasi (OS) adalah perangkat lunak yang bertindak sebagai perantara antara pengguna dan perangkat keras komputer. Tanpa sistem operasi, pengguna harus berinteraksi langsung dengan perangkat keras menggunakan bahasa mesin — sesuatu yang sangat tidak praktis. Sistem operasi populer saat ini meliputi Windows, macOS, Linux, Android, dan iOS.</p>
<p>Fungsi utama sistem operasi mencakup manajemen proses, manajemen memori, manajemen file system, dan manajemen perangkat I/O. Manajemen proses bertanggung jawab untuk menjadwalkan eksekusi program-program yang berjalan secara bersamaan. Algoritma penjadwalan seperti Round Robin, First Come First Served (FCFS), dan Shortest Job First (SJF) digunakan untuk mengalokasikan waktu CPU secara adil di antara proses-proses yang bersaing.</p>
<p>Manajemen memori bertugas mengalokasikan dan membebaskan ruang memori sesuai kebutuhan proses. Teknik seperti paging dan segmentation memungkinkan sistem operasi untuk mengelola memori secara efisien, bahkan ketika total kebutuhan memori melebihi kapasitas RAM fisik melalui mekanisme virtual memory. Konsep ini memungkinkan program yang lebih besar dari RAM fisik untuk tetap berjalan dengan memanfaatkan ruang di hard disk sebagai ekstensi memori.</p>

<h2>Bab 4: Jaringan Komputer</h2>
<p>Jaringan komputer adalah kumpulan dua atau lebih komputer yang saling terhubung untuk berbagi data dan sumber daya. Internet, jaringan terbesar di dunia, menghubungkan miliaran perangkat di seluruh dunia. Pemahaman tentang jaringan komputer sangat penting bagi seorang insinyur informatika karena hampir semua aplikasi modern membutuhkan konektivitas jaringan.</p>
<p>Model OSI (Open Systems Interconnection) membagi komunikasi jaringan menjadi tujuh lapisan: Physical, Data Link, Network, Transport, Session, Presentation, dan Application. Setiap lapisan memiliki tanggung jawab spesifik dan berkomunikasi dengan lapisan di atas dan di bawahnya. Model TCP/IP, yang lebih sederhana dengan empat lapisan, menjadi standar de facto untuk komunikasi internet.</p>
<p>Protokol-protokol penting dalam jaringan komputer meliputi TCP (Transmission Control Protocol) untuk komunikasi yang andal, UDP (User Datagram Protocol) untuk komunikasi yang cepat namun tidak dijamin, HTTP/HTTPS untuk transfer halaman web, DNS (Domain Name System) untuk penerjemahan nama domain ke alamat IP, dan DHCP (Dynamic Host Configuration Protocol) untuk alokasi alamat IP secara otomatis.</p>
<p>Keamanan jaringan menjadi perhatian utama di era digital. Ancaman seperti malware, phishing, DDoS attacks, dan man-in-the-middle attacks mengharuskan implementasi berbagai mekanisme keamanan. Firewall, enkripsi SSL/TLS, VPN (Virtual Private Network), dan sistem deteksi intrusi (IDS) adalah beberapa alat yang digunakan untuk melindungi jaringan dan data dari ancaman siber.</p>

<h2>Bab 5: Algoritma dan Struktur Data</h2>
<p>Algoritma adalah urutan langkah-langkah logis dan sistematis untuk menyelesaikan suatu masalah. Dalam ilmu komputer, efisiensi algoritma diukur menggunakan notasi Big-O yang menggambarkan hubungan antara ukuran input dan waktu atau ruang yang dibutuhkan. Algoritma yang efisien dapat menghemat jutaan dolar dalam biaya komputasi pada skala besar.</p>
<p>Struktur data adalah cara mengorganisir dan menyimpan data agar dapat diakses dan dimodifikasi secara efisien. Struktur data dasar meliputi array, linked list, stack, queue, tree, dan graph. Pemilihan struktur data yang tepat sangat memengaruhi kinerja sebuah program. Misalnya, hash table memungkinkan pencarian data dengan waktu konstan O(1), sementara pencarian pada array yang tidak terurut membutuhkan waktu linear O(n).</p>
<p>Algoritma pengurutan (sorting) seperti Bubble Sort, Merge Sort, Quick Sort, dan Heap Sort adalah topik fundamental yang wajib dikuasai. Merge Sort dan Quick Sort memiliki kompleksitas waktu O(n log n) pada kasus rata-rata, menjadikannya jauh lebih efisien daripada Bubble Sort yang memiliki kompleksitas O(n²) untuk dataset berukuran besar.</p>'
WHERE `id` = 1;

-- =============================================
-- UPDATE BUKU 2: Pemrograman Web
-- =============================================
UPDATE `books` SET 
  `author` = 'Ir. Budi Raharjo, S.Kom., M.T.',
  `description` = 'Panduan praktis membangun website modern menggunakan HTML, CSS, JavaScript, PHP, dan MySQL. Dilengkapi studi kasus proyek nyata untuk pemula hingga menengah.',
  `price` = 75000,
  `publisher` = 'Penerbit Andi Yogyakarta',
  `publication_date` = '2024-06-20',
  `content` = '<h2>Bab 1: Pengantar Pemrograman Web</h2>
<p>Pemrograman web adalah proses pembuatan aplikasi yang berjalan di atas platform web menggunakan teknologi seperti HTML, CSS, dan JavaScript. Berbeda dengan aplikasi desktop tradisional yang diinstal langsung di komputer pengguna, aplikasi web diakses melalui browser dan dapat digunakan dari mana saja selama terhubung ke internet. Ini menjadikan pemrograman web sebagai keterampilan yang sangat diminati di era digital saat ini.</p>
<p>Sejarah web dimulai pada tahun 1989 ketika Tim Berners-Lee, seorang ilmuwan di CERN, mengusulkan sistem hypertext untuk berbagi informasi di antara peneliti. Proposal ini kemudian berkembang menjadi World Wide Web (WWW) yang kita kenal sekarang. Halaman web pertama dipublikasikan pada tahun 1991, dan sejak saat itu web telah mengalami transformasi besar — dari halaman statis sederhana hingga aplikasi interaktif yang kompleks seperti Google Maps, Facebook, dan Netflix.</p>
<p>Dalam pengembangan web, terdapat dua sisi utama: front-end (client-side) dan back-end (server-side). Front-end bertanggung jawab atas tampilan dan interaksi yang dilihat pengguna, menggunakan HTML untuk struktur, CSS untuk gaya visual, dan JavaScript untuk interaktivitas. Back-end menangani logika bisnis, pengolahan data, dan komunikasi dengan basis data, menggunakan bahasa seperti PHP, Python, Ruby, atau Node.js.</p>

<h2>Bab 2: HTML - Struktur Halaman Web</h2>
<p>HyperText Markup Language (HTML) adalah bahasa markup standar yang digunakan untuk membuat struktur halaman web. HTML bukan bahasa pemrograman, melainkan bahasa markup yang menggunakan tag-tag untuk mendefinisikan elemen-elemen pada halaman. Versi terbaru, HTML5, memperkenalkan banyak fitur baru seperti elemen semantik, dukungan multimedia native, dan API untuk grafis dan penyimpanan lokal.</p>
<p>Setiap dokumen HTML dimulai dengan deklarasi DOCTYPE yang memberitahu browser versi HTML yang digunakan. Struktur dasar HTML terdiri dari elemen html yang membungkus seluruh konten, elemen head yang berisi metadata seperti judul halaman dan link ke stylesheet, dan elemen body yang berisi konten yang ditampilkan kepada pengguna.</p>
<p>Elemen-elemen semantik HTML5 seperti header, nav, main, article, section, aside, dan footer memberikan makna struktural pada konten halaman. Penggunaan elemen semantik tidak hanya meningkatkan aksesibilitas bagi pembaca layar dan teknologi asistif lainnya, tetapi juga membantu mesin pencari memahami struktur dan konten halaman dengan lebih baik, sehingga berdampak positif pada SEO.</p>

<h2>Bab 3: CSS - Mendesain Tampilan Web</h2>
<p>Cascading Style Sheets (CSS) adalah bahasa yang digunakan untuk mendeskripsikan tampilan visual elemen-elemen HTML. Dengan CSS, pengembang dapat mengontrol warna, font, ukuran, posisi, dan berbagai aspek visual lainnya. Pemisahan antara struktur (HTML) dan presentasi (CSS) merupakan prinsip fundamental dalam pengembangan web modern yang memudahkan pemeliharaan dan konsistensi desain.</p>
<p>CSS3, versi terbaru, memperkenalkan fitur-fitur canggih seperti animasi, transisi, gradien, shadow, border-radius, dan media queries. Flexbox dan Grid Layout adalah dua sistem tata letak yang sangat powerful untuk menciptakan layout responsif tanpa perlu menggunakan framework eksternal. Flexbox ideal untuk tata letak satu dimensi (baris atau kolom), sementara Grid cocok untuk tata letak dua dimensi.</p>
<p>Responsif design adalah pendekatan desain yang memastikan halaman web tampil dengan baik di berbagai ukuran layar — dari smartphone hingga monitor desktop besar. Media queries memungkinkan pengembang menerapkan gaya CSS yang berbeda berdasarkan karakteristik perangkat seperti lebar layar, orientasi, dan resolusi. Pendekatan mobile-first, di mana desain dimulai dari layar terkecil kemudian ditingkatkan untuk layar yang lebih besar, telah menjadi standar industri.</p>

<h2>Bab 4: JavaScript - Interaktivitas dan Logika</h2>
<p>JavaScript adalah bahasa pemrograman yang membuat halaman web menjadi interaktif dan dinamis. Awalnya diciptakan oleh Brendan Eich di Netscape pada tahun 1995 dalam waktu hanya 10 hari, JavaScript kini telah berkembang menjadi salah satu bahasa pemrograman paling populer di dunia. Dengan Node.js, JavaScript bahkan dapat digunakan di sisi server, menjadikannya bahasa yang truly full-stack.</p>
<p>Konsep fundamental JavaScript meliputi variabel, tipe data, operator, struktur kontrol (if-else, switch, loop), fungsi, dan objek. JavaScript mendukung paradigma pemrograman prosedural, berorientasi objek (meskipun berbasis prototipe, bukan kelas tradisional), dan fungsional. ES6 (ECMAScript 2015) memperkenalkan fitur-fitur modern seperti let/const, arrow functions, template literals, destructuring, dan modul.</p>
<p>DOM (Document Object Model) manipulation adalah salah satu aspek terpenting JavaScript di browser. DOM merepresentasikan struktur HTML sebagai pohon objek yang dapat dimanipulasi menggunakan JavaScript. Dengan DOM API, pengembang dapat menambah, menghapus, atau mengubah elemen HTML secara dinamis, merespons interaksi pengguna, dan memperbarui konten halaman tanpa perlu memuat ulang seluruh halaman.</p>

<h2>Bab 5: PHP dan MySQL - Back-End Development</h2>
<p>PHP (Hypertext Preprocessor) adalah bahasa pemrograman server-side yang dirancang khusus untuk pengembangan web. Diciptakan oleh Rasmus Lerdorf pada tahun 1995, PHP telah menjadi bahasa back-end paling banyak digunakan, menggerakkan lebih dari 75% website di seluruh dunia termasuk WordPress, Facebook (awalnya), dan Wikipedia.</p>
<p>MySQL adalah sistem manajemen basis data relasional (RDBMS) open-source yang paling populer. MySQL menggunakan Structured Query Language (SQL) untuk mengelola data. Operasi dasar CRUD — Create (INSERT), Read (SELECT), Update (UPDATE), dan Delete (DELETE) — menjadi fondasi interaksi dengan basis data dalam aplikasi web.</p>
<p>Integrasi PHP dan MySQL memungkinkan pembuatan aplikasi web dinamis yang menyimpan dan mengambil data dari basis data. Penggunaan prepared statements sangat penting untuk mencegah SQL injection, salah satu serangan keamanan web paling umum. Framework PHP modern seperti Laravel menyederhanakan proses pengembangan dengan menyediakan fitur-fitur seperti ORM (Eloquent), routing, middleware, dan template engine (Blade).</p>'
WHERE `id` = 2;

-- =============================================
-- UPDATE BUKU 3: JavaScript
-- =============================================
UPDATE `books` SET 
  `author` = 'Rizky Maulana Hidayat, S.T.',
  `description` = 'Menguasai JavaScript dari dasar hingga mahir. Membahas ES6+, DOM, async/await, OOP, dan pengembangan aplikasi web interaktif modern.',
  `price` = 95000,
  `publisher` = 'Gramedia Pustaka Utama',
  `publication_date` = '2024-01-10',
  `content` = '<h2>Bab 1: Mengenal JavaScript</h2>
<p>JavaScript adalah bahasa pemrograman tingkat tinggi yang awalnya dirancang untuk menambahkan interaktivitas pada halaman web. Diciptakan oleh Brendan Eich pada tahun 1995, JavaScript telah berevolusi dari bahasa scripting sederhana menjadi bahasa pemrograman serbaguna yang dapat digunakan untuk pengembangan front-end, back-end, mobile, desktop, hingga Internet of Things (IoT).</p>
<p>Nama JavaScript sering menimbulkan kebingungan karena kemiripannya dengan Java, padahal keduanya adalah bahasa yang sangat berbeda. JavaScript memiliki typing yang dinamis, mendukung first-class functions, dan menggunakan prototype-based inheritance, sementara Java adalah bahasa yang strongly-typed dengan class-based inheritance. Standar resmi JavaScript dikenal sebagai ECMAScript, yang dikelola oleh organisasi ECMA International.</p>
<p>Ekosistem JavaScript sangat luas dan terus berkembang. Di sisi client, terdapat framework dan library seperti React, Vue.js, Angular, dan Svelte. Di sisi server, Node.js memungkinkan JavaScript berjalan di luar browser. Untuk pengembangan mobile, ada React Native dan Ionic. Untuk desktop, Electron memungkinkan pembuatan aplikasi desktop menggunakan teknologi web. Package manager npm menyediakan lebih dari satu juta paket open-source yang dapat digunakan oleh pengembang.</p>

<h2>Bab 2: Variabel, Tipe Data, dan Operator</h2>
<p>Variabel adalah wadah untuk menyimpan nilai data. Dalam JavaScript modern (ES6+), terdapat tiga cara mendeklarasikan variabel: var, let, dan const. Kata kunci var memiliki scope function-level dan bersifat hoisted, sementara let dan const memiliki scope block-level yang lebih prediktif. Const digunakan untuk nilai yang tidak akan diubah setelah inisialisasi, sementara let untuk nilai yang mungkin berubah.</p>
<p>JavaScript memiliki tujuh tipe data primitif: string (teks), number (angka), boolean (true/false), null (ketiadaan nilai yang disengaja), undefined (belum diberi nilai), symbol (identifikasi unik), dan BigInt (angka besar). Selain itu, terdapat tipe data objek yang mencakup plain objects, arrays, functions, Date, RegExp, dan lainnya. JavaScript bersifat dynamically typed, artinya variabel tidak terikat pada satu tipe data.</p>
<p>Operator dalam JavaScript dibagi menjadi beberapa kategori: operator aritmatika (+, -, *, /, %, **), operator penugasan (=, +=, -=, *=), operator perbandingan (==, ===, !=, !==, <, >, <=, >=), operator logika (&&, ||, !), dan operator lainnya. Penting untuk memahami perbedaan antara == (loose equality) dan === (strict equality). Operator === memeriksa nilai DAN tipe data, sehingga lebih aman digunakan untuk menghindari konversi tipe yang tidak diinginkan.</p>

<h2>Bab 3: Fungsi dan Scope</h2>
<p>Fungsi adalah blok kode yang dapat digunakan kembali untuk melakukan tugas tertentu. Dalam JavaScript, fungsi adalah first-class citizens, artinya mereka dapat disimpan dalam variabel, dikirim sebagai argumen, dan dikembalikan dari fungsi lain. Kemampuan ini membuat JavaScript sangat fleksibel dan mendukung paradigma pemrograman fungsional.</p>
<p>ES6 memperkenalkan arrow functions yang menyediakan sintaks yang lebih ringkas untuk mendefinisikan fungsi. Selain sintaks, arrow functions juga memiliki perbedaan penting dalam binding this — mereka mewarisi this dari scope di mana mereka didefinisikan (lexical this), berbeda dengan fungsi reguler yang memiliki this sendiri berdasarkan bagaimana mereka dipanggil.</p>
<p>Scope menentukan aksesibilitas variabel dalam kode. JavaScript memiliki global scope, function scope, dan block scope (diperkenalkan ES6). Closure terjadi ketika fungsi inner mengakses variabel dari fungsi outer yang sudah selesai dieksekusi. Closure adalah konsep powerful yang digunakan dalam berbagai pola pemrograman seperti module pattern, data privacy, dan function factories.</p>

<h2>Bab 4: Asynchronous JavaScript</h2>
<p>JavaScript adalah bahasa single-threaded, artinya hanya dapat mengeksekusi satu tugas pada satu waktu. Namun, banyak operasi seperti request jaringan, pembacaan file, dan timer membutuhkan waktu yang tidak pasti. Asynchronous programming memungkinkan JavaScript menangani operasi-operasi ini tanpa memblokir eksekusi kode lainnya.</p>
<p>Callbacks adalah pendekatan paling dasar untuk menangani operasi asynchronous. Sebuah callback function dikirim sebagai argumen dan dipanggil setelah operasi selesai. Namun, penggunaan callbacks yang berlebihan dapat menyebabkan callback hell — kode yang deeply nested dan sulit dibaca. Promises menawarkan solusi yang lebih elegan dengan menyediakan interface .then() dan .catch() untuk menangani keberhasilan dan kegagalan.</p>
<p>Async/await, diperkenalkan dalam ES2017, adalah syntactic sugar di atas Promises yang membuat kode asynchronous terlihat seperti kode synchronous. Kata kunci async di depan fungsi membuatnya selalu mengembalikan Promise, dan await di dalam fungsi async menghentikan eksekusi hingga Promise yang ditunggu diselesaikan. Kombinasi try-catch dapat digunakan untuk error handling yang bersih dan mudah dibaca.</p>

<h2>Bab 5: DOM Manipulation dan Event Handling</h2>
<p>Document Object Model (DOM) adalah representasi terstruktur dari dokumen HTML dalam bentuk pohon objek. Setiap elemen HTML menjadi node dalam pohon ini, dan JavaScript dapat memanipulasi node-node tersebut untuk mengubah konten, struktur, dan gaya halaman secara dinamis. DOM API menyediakan metode seperti getElementById, querySelector, createElement, appendChild, dan removeChild.</p>
<p>Event handling memungkinkan program merespons interaksi pengguna seperti klik mouse, penekanan tombol, penggeseran layar, dan lainnya. Method addEventListener adalah cara modern untuk mendaftarkan event handler. Event propagation — yang terdiri dari capturing phase dan bubbling phase — menentukan urutan di mana event handler dieksekusi ketika event terjadi pada elemen yang bersarang.</p>
<p>Teknik event delegation memanfaatkan event bubbling untuk menangani event pada banyak elemen anak menggunakan satu event handler pada elemen induk. Ini sangat efisien untuk daftar yang besar atau konten yang ditambahkan secara dinamis, karena mengurangi jumlah event handler yang perlu didaftarkan dan menghilangkan kebutuhan untuk menambahkan handler pada elemen baru.</p>'
WHERE `id` = 3;
